Course Recommendation Frontend
pennlabs/penn-courses pull request #280
Opened 2021-03-28 17:12 UTC by andyjiang3

• Added course rec frontend

Currently using search result for course recommendations
Need to link with the backend when it is finished

<img width="374" alt="Screen Shot 2021-03-28 at 1 05 13 PM" src="https://user-images.githubusercontent.com/44344658/112761011-147e0880-8fc7-11eb-9d48-e0d23ef50c3a.png">
<img width="377" alt="Screen Shot 2021-03-28 at 1 04 55 PM" src="https://user-images.githubusercontent.com/44344658/112761012-1778f900-8fc7-11eb-9f3f-9059419a6750.png">

2021-03-31 21:45 UTC, dlike230 requested changes
Overall, great work! Only thing (other than my inline comments) is I'm not sure how we should go about updating the recommendations displayed (if at all) when a user's schedules change. Right now, if a user adds new classes that would affect their recommendations, that would have no effect on the recommendations displayed until the user refreshed the page. We could update recommndations every time the schedule is updated, but that might result in too many API calls. I'm tagging @mureytasroc and @davish to get their input.

2021-03-31 21:45 UTC, dlike230 commented on frontend/plan/components/selector/Selector.tsx
> +    useEffect(() => {
This useEffect is missing some deps (such as setRecCourses)

2021-03-31 21:45 UTC, dlike230 commented on frontend/plan/components/selector/Selector.tsx
> +        fetch(`/api/plan/recommendations/`, requestOptions).then((res) =>
We have a helper function for this, I believe it's called doApiRequest

2021-03-31 22:08 UTC, mureytasroc commented
> Overall, great work! Only thing (other than my inline comments) is I'm not sure how we should go about updating the recommendations displayed (if at all) when a user's schedules change. Right now, if a user adds new classes that would affect their recommendations, that would have no effect on the recommendations displayed until the user refreshed the page. We could update recommndations every time the schedule is updated, but that might result in too many API calls. I'm tagging @mureytasroc and @davish to get their input.
> 
> **Edit:** We should probably also remove the "x" buttons next to recommendations, since they don't do anything.

What do you think about adding a refresh button to "refresh recommendations"?

2021-04-01 19:41 UTC, dlike230 commented
> > Overall, great work! Only thing (other than my inline comments) is I'm not sure how we should go about updating the recommendations displayed (if at all) when a user's schedules change. Right now, if a user adds new classes that would affect their recommendations, that would have no effect on the recommendations displayed until the user refreshed the page. We could update recommndations every time the schedule is updated, but that might result in too many API calls. I'm tagging @mureytasroc and @davish to get their input.
> > **Edit:** We should probably also remove the "x" buttons next to recommendations, since they don't do anything.
> 
> What do you think about adding a refresh button to "refresh recommendations"?

Seems like the best solution. Maybe for now we can just have recs update at a scheduled interval if changes have been made to the schedule?

2021-04-01 23:59 UTC, andyjiang3 commented
• Added star next to rec courses in the search list
• Added error messages
• Added refresh button 

<img width="374" alt="Screen Shot 2021-04-01 at 7 53 38 PM" src="https://user-images.githubusercontent.com/44344658/113365606-bd5c9880-9324-11eb-8325-62093adabd47.png">

2021-04-02 19:52 UTC, dlike230 requested changes
Just a couple really small things

2021-04-02 19:52 UTC, dlike230 commented on frontend/plan/components/recomendations/RecBanner.tsx
> +    const [disabled, setDisabled] = useState(false);
For the sake of clarity, let's call this `refreshDisabled`

2021-04-02 19:52 UTC, dlike230 commented on frontend/plan/components/recomendations/RecInfo.tsx
> +                    you have made to your PCP schedules since the last refresh.
Replace PCP with Penn Course Plan

2021-04-03 01:50 UTC, dlike230 approved these changes
LGTM!

2021-04-03 02:07 UTC, merged