Alert plan integration
pennlabs/penn-courses pull request #599
Opened 2024-03-01 21:48 UTC by luke-rt

Alert + Plan api connection

2024-03-01 22:08 UTC, esinx requested changes

2024-03-01 22:08 UTC, esinx commented on frontend/plan/components/alert/AlertForm.tsx
> +    setContactInfoBackend: (email: string, phone: string) => void;
Use `onChange` patterns!

2024-03-01 22:08 UTC, esinx commented on frontend/plan/components/alert/AlertForm.tsx
> +    alerts: {
`onAddAlert` and `onAlertRemove` as optional makes more sense

2024-03-01 22:08 UTC, esinx commented on frontend/plan/components/alert/AlertForm.tsx
> +    setShowForm: (show: boolean) => void;
Same here, we want to use optional callbacks

2024-03-01 22:08 UTC, esinx commented on backend/alert/util.py
> +    return True
revert changes

2024-03-04 18:31 UTC, luke-rt commented on frontend/plan/components/alert/AlertForm.tsx
> +            onClick={(e) => e.stopPropagation()}
i think i was having an issue with clicking a form selecting a cart item underneath, once I finalize the way the alert form looks ill figure out if i still need it though

2024-03-17 17:14 UTC, esinx requested changes
Good work Luke!! Just a few minor typescript details and we should be good to go, make sure to finish your todos / resolve hardcoded components

2024-03-17 17:14 UTC, esinx commented on frontend/plan/components/alert/Alerts.tsx
> +                        <AlertSection
To refactor

2024-03-17 17:14 UTC, esinx commented on frontend/plan/components/modals/AlertFormModal.tsx
> +export default function AlertForm({ onContactInfoChange, contactInfo, addAlert, close }: AlertFormProps) {
Let's try to use https://react-hook-form.com/

2024-03-17 17:14 UTC, esinx commented on frontend/plan/components/modals/AlertFormModal.tsx
> +// export default function AlertForm({ onContactInfoChange, contactInfo, addAlert, close }: AlertFormProps) {
Remove

2024-03-17 17:14 UTC, esinx commented on frontend/plan/pages/index.tsx
> +    const [showCart, setShowCart] = useState<boolean>(true);
remove `<boolean>`

2024-03-17 17:14 UTC, esinx commented on frontend/plan/components/selector/SectionList.tsx
>  }: SectionListProps & {
Give this type a name, let's avoid inline typing

2024-03-25 18:31 UTC, esinx commented
Could we use hash instead of query for having alerts tab open by default? Queries are often used for determining what content to be displayed(hence search "query"), whereas hashes are used for determining the landing position of the user.

2024-04-06 04:01 UTC, joyliu-q reviewed
Left some preliminary comments, please make sure to incorporate feedback from Courses leads.

2024-04-06 04:01 UTC, joyliu-q commented on frontend/plan/components/alert/AlertSection.tsx
> +        statuscolor = "#78d381";
Why is this not a constant?

2024-04-06 04:01 UTC, joyliu-q commented on frontend/plan/components/alert/AlertSection.tsx
> +        color: #d3d3d800;
Ditto

2024-04-07 17:40 UTC, esinx commented on frontend/plan/actions/index.js
> +            return error.json();
Yes you need to throw the error instead so that the caller of the function can handle the error correctly

2024-04-07 17:48 UTC, esinx requested changes
I want more perfection.
Good work.

2024-04-07 17:48 UTC, esinx commented on frontend/plan/pages/index.tsx
> +    }, [setShowAlerts]);
Unacceptable.

2024-04-07 17:48 UTC, esinx commented on frontend/plan/pages/index.tsx
> +    }, [setShowAlerts]);
Index page will be rerendered anyways; and you want to extract the hash router value as the component is rendering(or else user will see a page with the incorrect state). Set the default state value to depend on router instead.

2024-04-07 17:48 UTC, esinx commented on frontend/plan/pages/index.tsx
>                              <Cart setTab={setTab} mobileView={true} />
Bad prop name; use onChange, don't hardcode `mobileView`, could be a context or a hook to decide if user is using mobile view

2024-04-14 17:56 UTC, esinx approved these changes

2024-04-14 17:56 UTC, merged